version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: ${UID}:${GID}
    networks:
      - proxy
    volumes:
      - ./srv:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser-secure.entrypoints=websecure
      - traefik.http.routers.filebrowser-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.filebrowser-secure.tls=true
      - traefik.http.routers.filebrowser-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
