version: "3"
services:
  bookstack:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.bookstack.loadbalancer.server.port=80
      - traefik.http.routers.bookstack.entrypoints=http
      - traefik.http.routers.bookstack.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.bookstack-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.bookstack.middlewares=bookstack-https-redirect
      - traefik.http.routers.bookstack-secure.entrypoints=https
      - traefik.http.routers.bookstack-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.bookstack-secure.tls=true
      - traefik.http.routers.bookstack-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true
