version: '3'
services:
  webdav:
    image: atareao/webdav:v1.1
    container_name: webdav
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./share:/share
    environment:
      USERNAME: user
      PASSWORD: passwd
